// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "Tasks"

// Task mapped from table <Tasks>
type Task struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	Name      string    `gorm:"column:name;not null" json:"name"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
